name: Hello World

on:
  workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Print Hello World
        run: echo Hello Everyone!
